#!/bin/bash

ROOT_DIR=/var/www/recipes
TMP_DIR=$ROOT_DIR/tmp
XSL_DIR=$ROOT_DIR/xsl
XML_DIR=$ROOT_DIR/xml
HTML_DIR=$ROOT_DIR/html

CHEF_ID=$1

xmlstarlet tr $XSL_DIR/chef.xsl $XML_DIR/chefs/$CHEF_ID.xml  > $HTML_DIR/chefs/$CHEF_ID.html
