#!/bin/bash

ROOT_DIR=/var/www/recipes
TMP_DIR=$ROOT_DIR/tmp
XML_DIR=$ROOT_DIR/xml
XSL_DIR=$ROOT_DIR/xsl
HTML_DIR=$ROOT_DIR/html

SCRIPT_NAME=`basename $0`;

RECIPE_ID=$1

if [ -z "$2" ]; then
	echo "Usage: $SCRIPT_NAME <RECIPE_ID> <'newest'|'oldest'|'highest_rated'>";
	exit;
fi
if [ "$2" != "newest" -a "$2" != "oldest" -a "$2" != "highest_rated" ]; then
	echo "Usage: $SCRIPT_NAME <RECIPE_ID> <'newest'|'oldest'|'highest_rated'>";
	exit;
fi

xmlstarlet tr $XSL_DIR/reviews/recipe.xsl -s orderby=$2 $XML_DIR/meta/recipes/$RECIPE_ID.xml > $HTML_DIR/reviews/recipe/$2/$RECIPE_ID.html

